openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "POC for API Documentation"
    description:  "POC for API Doc Design and Collaboration"
servers:
    - url: https://localhost:9292
tags:
  - name: Examples

paths:
    /api/emaples:
        $ref: "./paths/examples/examples.yaml"
    /api/emaples/{exampleId}:
        $ref: "./paths/examples/example.yaml"
components:
    parameters:
        $ref: "./parameters/_index.yaml"
    schemas:
        $ref: "./schemas/_index.yaml"
    securitySchemes:
        $ref: "./securitySchemas/_index.yaml"
            
security:
    - ApiKey: []

